[package]
name = "red_black_tree"
version = "0.1.0"
authors = ["Paul Faria <Nashenas88@gmail.com>"]

[dependencies]
stainless = { git = "https://github.com/reem/stainless" }

[dev-dependencies]
expectest = "0.4.*"